apiVersion: v1
kind: Namespace
metadata:
  name: autoscaler-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  namespace: autoscaler-test
spec:
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
        - name: stress
          image: progrium/stress
          command: ['sh', '-c', "stress --cpu 1"]
          
